### ISSUE TITLE
Vicon markers

### ISSUE THREAD

**Issue by davidakhihiero** [Rooholla-KhorramBakht/vicon_bridge2#1]
does your version publish the transform of the labeled markers like the ros 1 version?

**Comment by Rooholla-KhorramBakht** [comment]
Hi, the node publishes TF2 and `geometry_msgs/msg/PoseStamped` for each defined object.

**Comment by davidakhihiero** [comment]
Okay, but what of for the markers themselves?

**Comment by Rooholla-KhorramBakht** [comment]
This feature is now implemented.

**Comment by davidakhihiero** [comment]
Great!
